const images = [
  '/img-carrossel/IMG_1.jpg',
  '/img-carrossel/IMG_2.jpg',
  '/img-carrossel/IMG_3.jpg',
  '/img-carrossel/IMG_4.jpg',
  '/img-carrossel/IMG_5.jpg',
  '/img-carrossel/IMG_6.jpg',
  '/img-carrossel/IMG_7.jpg',
  '/img-carrossel/IMG_8.jpg',
  '/img-carrossel/IMG_9.jpg',
  '/img-carrossel/IMG_10.jpg',
  '/img-carrossel/IMG_11.jpg',
  '/img-carrossel/IMG_12.jpg',
  '/img-carrossel/IMG_13.jpg',
  '/img-carrossel/IMG_14.jpg',
  '/img-carrossel/IMG_16.jpg',
  '/img-carrossel/IMG_17.jpg',
  '/img-carrossel/IMG_18.jpg',
  '/img-carrossel/IMG_20.jpg',
  '/img-carrossel/IMG_21.jpg',
  '/img-carrossel/IMG_22.jpg',
  '/img-carrossel/IMG_23.jpg',
  '/img-carrossel/IMG_24.jpg',
  '/img-carrossel/IMG_25.jpg',
  '/img-carrossel/IMG_26.jpg',
  '/img-carrossel/IMG_27.jpg',
  '/img-carrossel/IMG_28.jpg',
  '/img-carrossel/IMG_29.jpg',
];

export default images;